apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-rtt5
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-rtt5@sha256:a0be9ab6081a3074ddf73ec8b7565b760d40658af1319e0f86676bba2dc17e5c
        name: my-nodejs
        resources: {}
status: {}
